name: DEV - TEST CHANGE MY NAME Deploy to Keycloak Infrastructure As Code
on:
  workflow_dispatch:
jobs:
  keycloak-infrastructure-as-code:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      # - name: download dependencies
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"
      # - run: cd tools/config && npm ci
      - name: run script
        uses: actions/github-script@v7
        env:
          KC_REALM_ID: "${{ secrets.KC_REALM_ID }}"
          KC_ENVIRONMENT: "dev"
          KC_CLIENT_ID: ${{ secrets.KC_CLIENT_ID }}
          KC_CLIENT_SECRET: ${{ secrets.KC_CLIENT_SECRET }}
        with:
          script: |
            const { main } = require('./tools/iac/script.js');
            await main();
      - run: echo "🍏 This job's status is ${{ job.status }}."
