name: Create Tag

# this action will create a tag from either release-master or master branch on github.
# it will also tag the image in openshift at the same time.
# one this is done, we can run the deploy-to-dev or deploy-efxdev action to bring it into the environment.
# if we want to run this action again for the same tag number (ex. there are additional changes needed), we will have to delete it on github first before rerunning it.

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.ECER_NAMESPACE_NO_ENV }}-tools

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number in x.x.x format ex. 1.0.0"
        default: "1.1.1"
        required: true

jobs:
  openshift-ci-cd:
    name: Tag Image
    # ubuntu-latest can also be used.
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: Check User Input and branch
        run: |
          regex='^[0-9]+\.[0-9]+\.[0-9]+$'
          if [[ "${{github.event.inputs.version}}" =~ $regex ]]; then
            echo user input validated ${{github.event.inputs.version}}
          else
            echo ::error::input must be in x.x.x format your input was ${{github.event.inputs.version}}
            exit 1
          fi

          if [[ "${{github.ref_name}}" == "master" ]] || [[ "${{github.ref_name}}" == "release/master" ]]; then
            echo branch validated ${{github.ref_name}}
            if [[ "${{github.ref_name}}" == "master" ]]; then
              echo "IMAGETAG=master" >> $GITHUB_ENV
            else if [[ "${{github.ref_name}}" == "release/master" ]]; then
              echo "IMAGETAG=release-master" >> $GITHUB_ENV
            fi
          else
            echo ::error:: we must run workflow from master or release/master branch your branch was ${{github.ref_name}}
            exit 1
          fi

      # - name: Check out repository
      #   uses: actions/checkout@v3

      # - name: Create tag
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       console.log(`this action was run on branch :: ${context.ref}`);
      #       console.log(`SHA :: ${context.sha}`);
      #       console.log(`Action run by :: ${context.actor}`);

      #       await github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/${{ github.event.inputs.version }}',
      #         sha: context.sha
      #       })

      # - name: Install oc
      #   uses: redhat-actions/openshift-tools-installer@v1
      #   with:
      #     oc: 4

      # https://github.com/redhat-actions/oc-login#readme
      - uses: actions/checkout@v3
      - name: Tag in OpenShift
        needs: check-user-input
        run: |
          echo $IMAGETAG
          # set -eux
          # # Login to OpenShift and select project
          # oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
          # oc project ${{ env.OPENSHIFT_NAMESPACE }}

          # oc tag -n ${{env.OPENSHIFT_NAMESPACE}} registry-portal:${{github.event.inputs.version}} registry-portal:${{github.event.inputs.version}}
          # oc tag -n ${{env.OPENSHIFT_NAMESPACE}} api:${{github.event.inputs.version}} api:${{github.event.inputs.version}}
