name: Lets speed up OC install

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:

jobs:
  openshift-cd:
    name: I only install OC
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        id: install-cli
        with:
          oc: 4.18.17
          skip_cache: true
      - name: Print installed OC info
        run: |
          echo "OC installation details:"
          echo "${{ toJson(steps.install-cli.outputs)}}"
          echo "${{ toJSON(steps.install-cli.outputs.installed) }}"
